name: detool64
description: "An android application to view and optionally modify the save files of Shadow Fight 2 Definitve Edition"
publish_to: 'none'

version: 0.0.1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^11.3.1
  cupertino_icons: ^1.0.8
  fluttertoast: ^8.2.12
  xml: ^6.5.0
  path_provider: ^2.1.5
  signals: ^6.0.2
  http: ^1.4.0
  shared_preferences: ^2.5.3
  package_info_plus: ^8.3.0
  url_launcher: ^6.3.1
  dynamic_color: ^1.7.0
  share_plus: ^11.0.0
  file_picker: ^10.1.9
  toml: ^0.16.0
  uuid: ^4.5.1
  log_plus: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/sword.png
    - assets/images/house.png
    - assets/images/file.png
    - assets/images/wrench.png
    - assets/images/coin.png
    - assets/images/ruby.png
    - assets/images/forge_green.png
    - assets/images/forge_red.png
    - assets/images/forge_purple.png
    - assets/images/dojo.png
    - assets/images/lighting.png
    - assets/images/anvil.png
    - assets/images/katana.png
    - assets/images/shuriken.png
    - assets/images/amulet.png
    - assets/images/armor.png
    - assets/images/helm.png
    - assets/images/weapons.png
    - assets/images/treasure-chest.png
    - assets/xml/defaultRecord.xml
    - assets/enchantments/simple.toml
    - assets/enchantments/medium.toml
    - assets/enchantments/complex_1.toml
    - assets/enchantments/complex_2.toml
    - assets/enchantments/complex_3.toml
    - assets/enchantments/complex_4.toml
    - assets/enchantments/special_1.toml
    - assets/enchantments/special_2.toml
    - assets/enchantments/special_3.toml
    - assets/item_database/weapon.toml
    - assets/item_database/ranged.toml
    - assets/item_database/magic.toml
    - assets/item_database/armor.toml
    - assets/item_database/helm.toml
    - assets/traits.toml
