[group]
id = "complex_2"
displayName = "Complex II"
color = "0xFF441752"
order = 3
hasAspect = false

[karma]
name = "Karma"
id = "PERK_SKANDA_SET_KARMA"

[squall]
name = "Squall"
id = "PERK_GUST_SET_WIND_MAKER"

[plot_twist]
name = "Plot Twist"
id = "PERK_DIRECTOR_SET_PLOT_TWIST"

[time_shift]
name = "Time Shift"
id = "PERK_TIME_SHIFT_SET_TIME_SHIFTER"
