[group]
id = "special_4"
displayName = "Elixir's"
color = "0xFAE251AA"
order = 7
hasAspect = false

[lightning_chain]
name = "Lightning Chain"
id = "PERK_LIGHTING_CHAIN"

[fear_ray]
name = "Fear Ray"
id = "PERK_FEAR_RAY"

[power_field]
name = "Power Field"
id = "PERK_POWER_FIELD"

[grasp_of_darkness]
name = "Grasp of Darkness"
id = "PERK_GRASP_OF_DARKNESS"

[titans_shield]
name = "Hex Shield"
id = "PERK_TITANS_SHIELD"
