name: saturn_web
description: "Saturn Web Application2"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  xml: ^6.5.0
  toml: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/toml/armor.toml
    - assets/toml/complex_1.toml
    - assets/toml/complex_2.toml
    - assets/toml/complex_3.toml
    - assets/toml/helm.toml
    - assets/toml/magic.toml
    - assets/toml/medium.toml
    - assets/toml/ranged.toml
    - assets/toml/simple.toml
    - assets/toml/special_1.toml
    - assets/toml/special_2.toml
    - assets/toml/special_3.toml
    - assets/toml/traits.toml
    - assets/toml/weapon.toml
