[group]
id = "special_2"
displayName = "Special II"
color = "0xFAE251AA"
order = 6
hasAspect = false

[teleportation]
name = "Teleportation"
id = "PERK_TELEPORTATION"

[assistants]
name = "Call to Arms"
id = "PERK_ASSISTANTS"

[rat_wave]
name = "Rat Wave"
id = "PERK_RAT_WAVE"

[war_whirl]
name = "War Whirl"
id = "PERK_WAR_WHIRL"
