name: Build Stalker APK

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract Version from pubspec.yaml
        id: get_version
        run: |
          VERSION=$(grep 'version:' pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          echo "VERSION=v$VERSION" >> $GITHUB_ENV

      - name: Set up Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --release --no-shrink --android-skip-build-dependency-validation

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Saturn ${{ env.VERSION }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: build/app/outputs/flutter-apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Release Notification to Telegram
        if: success()
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
        run: |
          # Находим имя собранного APK файла
          APK_NAME=$(basename $(find build/app/outputs/flutter-apk -name "*.apk" | head -n 1))
          
          # Формируем прямую ссылку на скачивание asset из релиза
          DOWNLOAD_URL="https://github.com/${{ github.repository }}/releases/download/${{ env.VERSION }}/${APK_NAME}"
          RELEASE_PAGE="https://github.com/${{ github.repository }}/releases/tag/${{ env.VERSION }}"

          MESSAGE="🚀 *Saturn ${{ env.VERSION }} успешно собран\!*%0A%0A📦 *Файл:* \`${APK_NAME}\`%0A🔗 [Скачать APK](${DOWNLOAD_URL})%0A📑 [Страница релиза](${RELEASE_PAGE})"

          curl -s -X POST "https://api.telegram.org/bot${8906416209:AAFXJjL_ij0dSVRQ1_FF2XWtHsqeJTji7FI}/sendMessage" \
               -d "chat_id=${5576359465}" \
               -d "text=${MESSAGE}" \
               -d "parse_mode=MarkdownV2" \
               -d "disable_web_page_preview=true"
               